services:
  postgres:
    container_name: lucene-keycloak-postgres
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lucenedb
    ports:
      - "5432:5432"
    volumes:
      #      run this line only when initializing database initially with 2 databases
      #      - ./init.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql
      - ./docker/postgres/data:/var/lib/postgresql/data
  lucene-spring:
    container_name: lucene-backend
    image: rituraj49/lucene-demo
    restart: unless-stopped
    depends_on:
      - keycloak
    ports:
      - 8080:8080